name = "tomestone"
version = "0.1.0"
description = "A Gleam project"
target = "javascript"
licences = ["Apache-2.0"]
repository = { type = "github", user = "username", repo = "project" }
links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.27"
gleam_erlang = "~> 0.18"

[dev-dependencies]
gleeunit = "~> 0.10"
